/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quotes;

import com.google.gson.Gson;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void quoteTest(){
        // Using absolute path in any file
        String path1 = "C:\\Users\\hamzh\\Desktop\\Task\\java\\quotes\\app\\src\\test\\resources\\recentquotes.json";
        String json = App.fileReader(path1);
        Gson gson = new Gson();
        Quotes[] quotesArray = gson.fromJson(json, Quotes[].class);
        String res = String.valueOf(quotesArray[0]);
        String test = "Quotes{author='Marilyn Monroe', text='I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.'}" ;
        assertEquals(test , res);
    }


}
