/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;

public class App {


    public static void main(String[] args) {

        // Read file
        String path = "app/src/main/resources/recentquotes.json" ;
        String json = fileReader(path);


        Gson gson = new Gson();
        // https://howtodoinjava.com/gson/gson-parse-json-array/
        Quotes[] quotesArray = gson.fromJson(json, Quotes[].class);
        Random random = new Random();
        int max = quotesArray.length - 1 ;
        int randomNumber = random.nextInt(max + 1 );
        System.out.println(quotesArray[randomNumber]);


//        for(Quotes quote : quotesArray) {
//            System.out.println(quote);
//        }

    }

    public static String fileReader(String path){

        Path bufferPath = Paths.get(path);
        String json = "" ;
        try {
            BufferedReader reader = Files.newBufferedReader(bufferPath);
            String line = reader.readLine();
            while(line != null){
                json += line + "\n" ;
                line = reader.readLine();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return json ;
    }
}
